-- Create establishments table
CREATE TABLE public.establishments (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Create establishment_drinks table
CREATE TABLE public.establishment_drinks (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  establishment_id UUID NOT NULL REFERENCES public.establishments(id) ON DELETE CASCADE,
  category TEXT NOT NULL,
  category_label TEXT NOT NULL,
  drink_name TEXT NOT NULL,
  abv DECIMAL(5,2) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.establishments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.establishment_drinks ENABLE ROW LEVEL SECURITY;

-- Public read access for both tables
CREATE POLICY "Anyone can read establishments" ON public.establishments FOR SELECT USING (true);
CREATE POLICY "Anyone can read establishment drinks" ON public.establishment_drinks FOR SELECT USING (true);

-- Create indexes for performance
CREATE INDEX idx_establishment_drinks_establishment ON public.establishment_drinks(establishment_id);
CREATE INDEX idx_establishment_drinks_category ON public.establishment_drinks(category);

-- Insert Wetherspoons establishment
INSERT INTO public.establishments (name) VALUES ('Wetherspoons');

-- Insert all drinks for Wetherspoons
INSERT INTO public.establishment_drinks (establishment_id, category, category_label, drink_name, abv)
SELECT 
  (SELECT id FROM public.establishments WHERE name = 'Wetherspoons'),
  category,
  category_label,
  drink_name,
  abv
FROM (VALUES
  -- Beer (Pint)
  ('beer_pint', 'Beer (Pint)', 'Carling', 4.0),
  ('beer_pint', 'Beer (Pint)', 'Coors', 4.0),
  ('beer_pint', 'Beer (Pint)', 'Stella Artois', 4.6),
  ('beer_pint', 'Beer (Pint)', 'Budweiser', 4.5),
  ('beer_pint', 'Beer (Pint)', 'Corona', 4.5),
  ('beer_pint', 'Beer (Pint)', 'Heineken', 5.0),
  ('beer_pint', 'Beer (Pint)', 'Peroni', 5.1),
  ('beer_pint', 'Beer (Pint)', 'San Miguel', 5.0),
  ('beer_pint', 'Beer (Pint)', 'Amstel', 4.1),
  ('beer_pint', 'Beer (Pint)', 'Beck''s', 4.8),
  ('beer_pint', 'Beer (Pint)', 'Birra Moretti', 4.6),
  ('beer_pint', 'Beer (Pint)', 'Kronenbourg 1664', 5.0),
  ('beer_pint', 'Beer (Pint)', 'Foster''s', 4.0),
  ('beer_pint', 'Beer (Pint)', 'Tennent''s', 4.0),
  ('beer_pint', 'Beer (Pint)', 'Carlsberg', 3.8),
  ('beer_pint', 'Beer (Pint)', 'Guinness', 4.2),
  ('beer_pint', 'Beer (Pint)', 'Murphy''s', 4.0),
  ('beer_pint', 'Beer (Pint)', 'Doom Bar', 4.0),
  ('beer_pint', 'Beer (Pint)', 'London Pride', 4.1),
  ('beer_pint', 'Beer (Pint)', 'Tribute', 4.2),
  ('beer_pint', 'Beer (Pint)', 'Hobgoblin', 4.5),
  ('beer_pint', 'Beer (Pint)', 'Old Speckled Hen', 4.5),
  ('beer_pint', 'Beer (Pint)', 'Bombardier', 4.1),
  ('beer_pint', 'Beer (Pint)', 'Greene King IPA', 3.6),
  ('beer_pint', 'Beer (Pint)', 'Ruddles Best', 3.7),
  ('beer_pint', 'Beer (Pint)', 'Sharp''s Atlantic', 4.2),
  ('beer_pint', 'Beer (Pint)', 'Timothy Taylor''s Landlord', 4.3),
  ('beer_pint', 'Beer (Pint)', 'Wainwright', 4.1),
  ('beer_pint', 'Beer (Pint)', 'Theakston Best', 3.8),
  ('beer_pint', 'Beer (Pint)', 'Belhaven Best', 3.2),
  ('beer_pint', 'Beer (Pint)', 'Landlord', 4.3),
  -- Cider (Pint)
  ('cider_pint', 'Cider (Pint)', 'Strongbow', 5.0),
  ('cider_pint', 'Cider (Pint)', 'Strongbow Dark Fruit', 4.0),
  ('cider_pint', 'Cider (Pint)', 'Magners', 4.5),
  ('cider_pint', 'Cider (Pint)', 'Bulmers', 4.5),
  ('cider_pint', 'Cider (Pint)', 'Kopparberg Strawberry & Lime', 4.0),
  ('cider_pint', 'Cider (Pint)', 'Kopparberg Mixed Fruit', 4.0),
  ('cider_pint', 'Cider (Pint)', 'Old Mout Berries & Cherries', 4.0),
  ('cider_pint', 'Cider (Pint)', 'Old Mout Kiwi & Lime', 4.0),
  ('cider_pint', 'Cider (Pint)', 'Rekorderlig Strawberry-Lime', 4.0),
  ('cider_pint', 'Cider (Pint)', 'Rekorderlig Wild Berries', 4.0),
  ('cider_pint', 'Cider (Pint)', 'Aspall', 5.5),
  ('cider_pint', 'Cider (Pint)', 'Thatchers Gold', 4.8),
  ('cider_pint', 'Cider (Pint)', 'Thatchers Haze', 4.5),
  ('cider_pint', 'Cider (Pint)', 'Stowford Press', 4.5),
  ('cider_pint', 'Cider (Pint)', 'Weston''s Old Rosie', 6.8),
  -- Beer (Bottle)
  ('beer_bottle', 'Beer (Bottle)', 'Budweiser (330ml)', 4.5),
  ('beer_bottle', 'Beer (Bottle)', 'Corona (330ml)', 4.5),
  ('beer_bottle', 'Beer (Bottle)', 'Peroni (330ml)', 5.1),
  ('beer_bottle', 'Beer (Bottle)', 'Sol (330ml)', 4.2),
  ('beer_bottle', 'Beer (Bottle)', 'Desperados (330ml)', 5.9),
  ('beer_bottle', 'Beer (Bottle)', 'BrewDog Punk IPA (330ml)', 5.4),
  ('beer_bottle', 'Beer (Bottle)', 'Estrella Damm (330ml)', 4.6),
  ('beer_bottle', 'Beer (Bottle)', 'Heineken (330ml)', 5.0),
  ('beer_bottle', 'Beer (Bottle)', 'Stella Artois (330ml)', 4.6),
  ('beer_bottle', 'Beer (Bottle)', 'Beck''s (275ml)', 4.8),
  ('beer_bottle', 'Beer (Bottle)', 'Cobra (330ml)', 4.5),
  ('beer_bottle', 'Beer (Bottle)', 'Kingfisher (330ml)', 4.8),
  ('beer_bottle', 'Beer (Bottle)', 'San Miguel (330ml)', 5.0),
  ('beer_bottle', 'Beer (Bottle)', 'Moretti (330ml)', 4.6),
  ('beer_bottle', 'Beer (Bottle)', 'Tiger (330ml)', 5.0),
  -- Wine (175ml Glass)
  ('wine', 'Wine (175ml Glass)', 'House White', 12.0),
  ('wine', 'Wine (175ml Glass)', 'House Red', 13.0),
  ('wine', 'Wine (175ml Glass)', 'House Rosé', 12.0),
  ('wine', 'Wine (175ml Glass)', 'Pinot Grigio', 12.0),
  ('wine', 'Wine (175ml Glass)', 'Sauvignon Blanc', 12.5),
  ('wine', 'Wine (175ml Glass)', 'Chardonnay', 13.0),
  ('wine', 'Wine (175ml Glass)', 'Merlot', 13.5),
  ('wine', 'Wine (175ml Glass)', 'Cabernet Sauvignon', 13.5),
  ('wine', 'Wine (175ml Glass)', 'Shiraz', 14.0),
  ('wine', 'Wine (175ml Glass)', 'Malbec', 13.5),
  ('wine', 'Wine (175ml Glass)', 'Rioja', 13.5),
  ('wine', 'Wine (175ml Glass)', 'Pinot Noir', 13.0),
  ('wine', 'Wine (175ml Glass)', 'Zinfandel Rosé', 10.5),
  ('wine', 'Wine (175ml Glass)', 'Prosecco', 11.0),
  ('wine', 'Wine (175ml Glass)', 'Champagne', 12.0),
  -- Vodka
  ('vodka', 'Vodka', 'Smirnoff', 37.5),
  ('vodka', 'Vodka', 'Absolut', 40.0),
  ('vodka', 'Vodka', 'Grey Goose', 40.0),
  ('vodka', 'Vodka', 'Belvedere', 40.0),
  ('vodka', 'Vodka', 'Cîroc', 40.0),
  ('vodka', 'Vodka', 'Ketel One', 40.0),
  ('vodka', 'Vodka', 'Stolichnaya', 40.0),
  ('vodka', 'Vodka', 'Russian Standard', 40.0),
  ('vodka', 'Vodka', 'Finlandia', 40.0),
  ('vodka', 'Vodka', 'Skyy', 40.0),
  ('vodka', 'Vodka', 'Eristoff', 37.5),
  ('vodka', 'Vodka', 'Chase', 40.0),
  ('vodka', 'Vodka', 'Au Vodka', 40.0),
  -- Gin
  ('gin', 'Gin', 'Gordon''s', 37.5),
  ('gin', 'Gin', 'Tanqueray', 43.1),
  ('gin', 'Gin', 'Bombay Sapphire', 40.0),
  ('gin', 'Gin', 'Hendrick''s', 41.4),
  ('gin', 'Gin', 'Beefeater', 40.0),
  ('gin', 'Gin', 'Sipsmith', 41.6),
  ('gin', 'Gin', 'Whitley Neill', 43.0),
  ('gin', 'Gin', 'Monkey 47', 47.0),
  ('gin', 'Gin', 'The Botanist', 46.0),
  ('gin', 'Gin', 'Plymouth', 41.2),
  ('gin', 'Gin', 'Aviation', 42.0),
  ('gin', 'Gin', 'Edinburgh Gin', 43.0),
  ('gin', 'Gin', 'Silent Pool', 43.0),
  ('gin', 'Gin', 'Warner''s', 40.0),
  ('gin', 'Gin', 'Malfy', 41.0),
  ('gin', 'Gin', 'Roku', 43.0),
  ('gin', 'Gin', 'Brockmans', 40.0),
  ('gin', 'Gin', 'Gordon''s Pink', 37.5),
  ('gin', 'Gin', 'Whitley Neill Raspberry', 43.0),
  ('gin', 'Gin', 'Whitley Neill Rhubarb & Ginger', 43.0),
  -- Rum
  ('rum', 'Rum', 'Bacardi Carta Blanca', 37.5),
  ('rum', 'Rum', 'Captain Morgan Original', 35.0),
  ('rum', 'Rum', 'Captain Morgan Spiced', 35.0),
  ('rum', 'Rum', 'Havana Club 3 Year', 40.0),
  ('rum', 'Rum', 'Havana Club 7 Year', 40.0),
  ('rum', 'Rum', 'Kraken', 40.0),
  ('rum', 'Rum', 'Malibu', 21.0),
  ('rum', 'Rum', 'Sailor Jerry', 40.0),
  ('rum', 'Rum', 'Mount Gay', 40.0),
  ('rum', 'Rum', 'Appleton Estate', 40.0),
  ('rum', 'Rum', 'Diplomatico', 40.0),
  ('rum', 'Rum', 'Dead Man''s Fingers', 37.5),
  ('rum', 'Rum', 'Bumbu', 35.0),
  ('rum', 'Rum', 'Wray & Nephew', 63.0),
  -- Whisky
  ('whisky', 'Whisky', 'Jack Daniel''s', 40.0),
  ('whisky', 'Whisky', 'Jim Beam', 40.0),
  ('whisky', 'Whisky', 'Jameson', 40.0),
  ('whisky', 'Whisky', 'Johnnie Walker Red', 40.0),
  ('whisky', 'Whisky', 'Johnnie Walker Black', 40.0),
  ('whisky', 'Whisky', 'Famous Grouse', 40.0),
  ('whisky', 'Whisky', 'Bell''s', 40.0),
  ('whisky', 'Whisky', 'Glenfiddich 12', 40.0),
  ('whisky', 'Whisky', 'Glenlivet 12', 40.0),
  ('whisky', 'Whisky', 'Monkey Shoulder', 40.0),
  ('whisky', 'Whisky', 'Maker''s Mark', 45.0),
  ('whisky', 'Whisky', 'Buffalo Trace', 40.0),
  ('whisky', 'Whisky', 'Bulleit', 45.0),
  ('whisky', 'Whisky', 'Bushmills', 40.0),
  ('whisky', 'Whisky', 'Southern Comfort', 35.0),
  ('whisky', 'Whisky', 'Fireball', 33.0),
  ('whisky', 'Whisky', 'Woodford Reserve', 43.2),
  ('whisky', 'Whisky', 'Wild Turkey', 40.5),
  ('whisky', 'Whisky', 'Canadian Club', 40.0),
  -- Tequila
  ('tequila', 'Tequila', 'Jose Cuervo Silver', 38.0),
  ('tequila', 'Tequila', 'Jose Cuervo Gold', 38.0),
  ('tequila', 'Tequila', 'Patron Silver', 40.0),
  ('tequila', 'Tequila', 'Patron Reposado', 40.0),
  ('tequila', 'Tequila', 'Don Julio Blanco', 38.0),
  ('tequila', 'Tequila', 'Don Julio Reposado', 38.0),
  ('tequila', 'Tequila', 'Olmeca', 38.0),
  ('tequila', 'Tequila', 'Casamigos Blanco', 40.0),
  ('tequila', 'Tequila', 'El Jimador', 38.0),
  ('tequila', 'Tequila', '1800 Silver', 40.0),
  -- Brandy/Cognac
  ('brandy', 'Brandy/Cognac', 'Hennessy VS', 40.0),
  ('brandy', 'Brandy/Cognac', 'Hennessy VSOP', 40.0),
  ('brandy', 'Brandy/Cognac', 'Rémy Martin VSOP', 40.0),
  ('brandy', 'Brandy/Cognac', 'Courvoisier VS', 40.0),
  ('brandy', 'Brandy/Cognac', 'Martell VS', 40.0),
  ('brandy', 'Brandy/Cognac', 'Vecchia Romagna', 38.0),
  ('brandy', 'Brandy/Cognac', 'Metaxa 5 Star', 38.0),
  -- Liqueurs
  ('liqueur', 'Liqueurs', 'Baileys', 17.0),
  ('liqueur', 'Liqueurs', 'Kahlúa', 20.0),
  ('liqueur', 'Liqueurs', 'Amaretto Disaronno', 28.0),
  ('liqueur', 'Liqueurs', 'Cointreau', 40.0),
  ('liqueur', 'Liqueurs', 'Grand Marnier', 40.0),
  ('liqueur', 'Liqueurs', 'Tia Maria', 20.0),
  ('liqueur', 'Liqueurs', 'Frangelico', 20.0),
  ('liqueur', 'Liqueurs', 'Chambord', 16.5),
  ('liqueur', 'Liqueurs', 'Midori', 20.0),
  ('liqueur', 'Liqueurs', 'Sambuca', 38.0),
  ('liqueur', 'Liqueurs', 'Jägermeister', 35.0),
  ('liqueur', 'Liqueurs', 'Southern Comfort', 35.0),
  ('liqueur', 'Liqueurs', 'Drambuie', 40.0),
  ('liqueur', 'Liqueurs', 'Limoncello', 28.0),
  ('liqueur', 'Liqueurs', 'Pimm''s No.1', 25.0),
  ('liqueur', 'Liqueurs', 'Aperol', 11.0),
  ('liqueur', 'Liqueurs', 'Campari', 25.0),
  ('liqueur', 'Liqueurs', 'Archers', 18.0),
  ('liqueur', 'Liqueurs', 'Passoa', 17.0),
  -- Cocktails
  ('cocktails', 'Cocktails', 'Mojito', 10.0),
  ('cocktails', 'Cocktails', 'Cosmopolitan', 15.0),
  ('cocktails', 'Cocktails', 'Margarita', 13.0),
  ('cocktails', 'Cocktails', 'Pina Colada', 13.0),
  ('cocktails', 'Cocktails', 'Long Island Iced Tea', 22.0),
  ('cocktails', 'Cocktails', 'Sex on the Beach', 9.0),
  ('cocktails', 'Cocktails', 'Strawberry Daiquiri', 12.0),
  ('cocktails', 'Cocktails', 'Espresso Martini', 12.0),
  ('cocktails', 'Cocktails', 'Pornstar Martini', 14.0),
  ('cocktails', 'Cocktails', 'Woo Woo', 12.0),
  ('cocktails', 'Cocktails', 'Mai Tai', 14.0),
  ('cocktails', 'Cocktails', 'Blue Lagoon', 8.0),
  ('cocktails', 'Cocktails', 'Tequila Sunrise', 10.0),
  ('cocktails', 'Cocktails', 'Moscow Mule', 11.0),
  ('cocktails', 'Cocktails', 'Dark ''n'' Stormy', 11.0),
  ('cocktails', 'Cocktails', 'Aperol Spritz', 8.0),
  ('cocktails', 'Cocktails', 'Negroni', 24.0),
  ('cocktails', 'Cocktails', 'Old Fashioned', 32.0),
  ('cocktails', 'Cocktails', 'Whisky Sour', 15.0),
  ('cocktails', 'Cocktails', 'Gin Fizz', 12.0),
  ('cocktails', 'Cocktails', 'Tom Collins', 10.0),
  ('cocktails', 'Cocktails', 'Bloody Mary', 12.0),
  ('cocktails', 'Cocktails', 'Bellini', 6.0),
  ('cocktails', 'Cocktails', 'Mimosa', 8.0),
  -- Shots
  ('shots', 'Shots', 'Sambuca', 38.0),
  ('shots', 'Shots', 'Tequila', 38.0),
  ('shots', 'Shots', 'Jägermeister', 35.0),
  ('shots', 'Shots', 'Fireball', 33.0),
  ('shots', 'Shots', 'Goldschläger', 43.5),
  ('shots', 'Shots', 'Aftershock', 40.0),
  ('shots', 'Shots', 'Sourz Apple', 15.0),
  ('shots', 'Shots', 'Sourz Cherry', 15.0),
  ('shots', 'Shots', 'Baby Guinness', 17.0),
  ('shots', 'Shots', 'B-52', 24.0),
  ('shots', 'Shots', 'Kamikaze', 22.0),
  ('shots', 'Shots', 'Tequila Slammer', 38.0),
  ('shots', 'Shots', 'Lemon Drop', 20.0),
  ('shots', 'Shots', 'Jagerbomb', 20.0),
  ('shots', 'Shots', 'Skittles', 17.0),
  -- Alcopops/RTD
  ('alcopops', 'Alcopops/RTD', 'Smirnoff Ice', 4.0),
  ('alcopops', 'Alcopops/RTD', 'WKD Blue', 4.0),
  ('alcopops', 'Alcopops/RTD', 'WKD Iron Brew', 4.0),
  ('alcopops', 'Alcopops/RTD', 'VK Blue', 4.0),
  ('alcopops', 'Alcopops/RTD', 'VK Orange', 4.0),
  ('alcopops', 'Alcopops/RTD', 'Gordon''s Pink & Tonic Can', 5.0),
  ('alcopops', 'Alcopops/RTD', 'Gordon''s G&T Can', 5.0),
  ('alcopops', 'Alcopops/RTD', 'Whitley Neill Pink G&T Can', 5.0),
  ('alcopops', 'Alcopops/RTD', 'Jack Daniel''s & Coke Can', 5.0),
  ('alcopops', 'Alcopops/RTD', 'Captain Morgan & Coke Can', 5.0)
) AS t(category, category_label, drink_name, abv);